//! AUTH
export const OTP_REQUEST = 'OTP_REQUEST';
export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_ERROR = 'OTP_ERROR';
export const RESEND_OTP_REQUEST = 'RESEND OTP REQUEST';
export const RESEND_OTP_SUCCESS = 'RESEND OTP SUCCESS';
export const OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_ERROR = 'OTP_VERIFY_ERROR';

// ! On-Board
export const ONBOARD_REQUEST = 'ONBOARD_REQUEST';
export const ONBOARD_SUCCESS = 'ONBOARD_SUCCESS';
export const ONBOARD_ERROR = 'ONBOARD_ERROR';

// ! Dashboard
export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_ERROR = 'DASHBOARD_ERROR';

// ! Jobs
export const FETCHED_JOBS_REQUEST = 'FETCHED_JOBS_REQUEST';
export const FETCHED_JOBS_SUCCESS = 'FETCHED_JOBS_SUCCESS';
export const FETCHED_JOBS_ERROR = 'FETCHED_JOBS_ERROR';
export const ADD_JOB_REQUEST = 'ADD_JOB_REQUEST';
export const ADD_JOB_SUCCESS = 'ADD_JOB_SUCCESS';
export const ADD_JOB_ERROR = 'ADD_JOB_ERROR';

// ! Candidates
export const ADD_CANDIDATES_REQUEST = 'ADD_CANDIDATES_REQUEST';
export const ADD_CANDIDATES_SUCCESS = 'ADD_CANDIDATES_SUCCESS';
export const ADD_CANDIDATES_ERROR = 'ADD_CANDIDATES_ERROR';
